# Generated by Django 3.2.8 on 2023-08-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
    ]
