# Generated by Django 3.2.8 on 2023-09-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230827_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='recorded_session_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
