# Generated by Django 3.2.8 on 2023-09-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_session_recorded_session_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='is_complete',
            new_name='is_completed',
        ),
    ]
