# Generated by Django 3.2.8 on 2023-09-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230827_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='banner_image',
            field=models.ImageField(blank=True, default='student_banner/default.jpg', null=True, upload_to='student_banner'),
        ),
    ]
