# Generated by Django 3.2.8 on 2023-09-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='banner_image',
            field=models.ImageField(blank=True, default='/student_banner/default.jpg', null=True, upload_to='student_banner/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/student_profile/default.jpg', null=True, upload_to='student_profile/'),
        ),
    ]
